version: "3.9"

services:

  cassandra:
    image: cassandra:4.1
    container_name: epistemic-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - ./cassandra:/schema
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: lihil-api
    depends_on:
      - cassandra
      - redis
    volumes:
      - ./cassandra:/schema
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    container_name: epistemic-redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: expertise-worker
    depends_on:
      - redis
      - cassandra
    volumes:
      - ./cassandra:/schema
    command: celery -A app.worker worker --loglevel=info
